/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package GCMS.Pratica.Gradlee;

public class Library {
    public boolean someLibraryMethod() {
    	//teste
        return false;
    }
}
